### ISSUE TITLE
non cps method calling cps method does not throw CpsCallableInvocation as expected

### ISSUE THREAD

**Issue by natsen** [mlasevich/jenkins-pipeline-library-reference#2]
Hi,

identifying cps issues during development is critical to jenkins pipeline development. I am glad you are attempting to address it here. I am challenged with the same. I was trying to factor your repo to detect issues that you would normally see only when run on Jenkins i.e with cps transformation. For instance "a non cps method will fail in jenkins when it calls a cps transformed method". But I was not able to test that scenarios successfully with your implementation. I do not have insight into internal groovy:cps implementation or haven't attempted that yet. Can you help me figure out why the following test case fails. shouldn't it throw CpsCallableInvocation. The same script fails with ```expected to call WorkflowScript.nonCpsMethodCallingCpsMethod but wound up catching WorkflowScript.cpsMethod; see: https://jenkins.io/redirect/pipeline-cps-method-mismatches/``` when run on jenkins.

This test does NOT throw CpsCallableInvocation as expected. This test case fails
```groovy
def "ascpsscript"(){
        when:
        asCPSScript("""

import com.cloudbees.groovy.cps.NonCPS
                @ NonCPS
        public void nonCpsMethodCallingCpsMethod(){
            println "this is a non cps method"
            cpsMethod()
        }
        public void cpsMethodCallingNonCps(){
            println "this is a cps method calling non cps method"
            nonCpsMethodCallingCpsMethod()
            println "after:this is a cps method calling non cps method"
        }
        public void cpsMethod(){
            println "this is a cps method"
        }
        @NonCPS
        public nonCpsMethod(){
            println "this is a non cps method"
        }
        nonCpsMethodCallingCpsMethod()
        """)
        then:
        thrown CpsCallableInvocation;
    }
```

**Comment by mlasevich** [comment]
interesting, I can reproduce this.  I think I focused on running CPS code, and missed this use-case - which is important. I think there likely needs to be some extra checks inside for CPS failures. Will need to look into it further. Thank you.

**Comment by mlasevich** [comment]
I think I identified what is going on, but unsure of the full impact of this change. I believe this should resolve the issue. 

@natsen Please test in real-world use, I will do the same prior to merging

Thank you for reporting this, it explains an occasional oddity I have seen.

Also, the actual CPS code throws `IllegalStateException` in case of a mismatch, not a `CpsCallableInvocation`

**Comment by natsen** [comment]
@mlasevich 

Thank you for the quick fix.

invokeCPSMethod does not work as expected. This is making the similar call as the asCPSScript but with invokeCPSMethod. 
This test fails.
 ```groovy
def "test non cps calling  cps method"(){
        when:
        invokeCPSMethod(sut, "nonCpsMethodCallingCpsMethod")
        then:
                thrown IllegalStateException;
    }
```

sut
```groovy
import com.cloudbees.groovy.cps.NonCPS
                @ NonCPS
        public void nonCpsMethodCallingCpsMethod(){
            println "this is a non cps method"
            cpsMethod()
        }
        public void cpsMethodCallingNonCps(){
            println "this is a cps method calling non cps method"
            nonCpsMethodCallingCpsMethod()
            println "after:this is a cps method calling non cps method"
        }
        public void cpsMethod(){
            println "this is a cps method"
        }
        @NonCPS
        public nonCpsMethod(){
            println "this is a non cps method"
        }
```

**Comment by mlasevich** [comment]
Hmm, curious - `asCPSScript()` just compiles the script and then calls `invokeCPSMethod()` so there should be no difference between the two :-/

**Comment by mlasevich** [comment]
I am unable to replicate the second issue, but I added unit tests for most common scenarios (#4) - can you take a look and see if I am missing something
